In [4]:
import requests
import pandas as pd


url = "https://remoteok.com/api"


response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
data = response.json()


jobs = data[1:]


job_list = []
for job in jobs:
    job_list.append({
        "Company Name": job.get("company", "N/A"),
        "Job Role": job.get("position", "N/A"),
        "Location": job.get("location", "Remote"),
        "Tags": ", ".join(job.get("tags", [])) if job.get("tags") else "N/A"
    })


df = pd.DataFrame(job_list)


df.to_csv("remoteok_jobs.csv", index=False, encoding="utf-8")


print(f"✅ Data collected successfully! Total jobs: {len(df)}")
print("Saved as remoteok_jobs.csv")
df.head()

✅ Data collected successfully! Total jobs: 95
Saved as remoteok_jobs.csv

,Company Name,Job Role,Location,Tags
0,Bonfire Studios,Character Concept Artist,United States,"3d, support, recruiting"
1,Coins.ph,Strategy Manager,"Taguig City, Metro Manila, Philippines","manager, web3, crypto, cryptocurrencies, suppo..."
2,Aragon,Content &amp; Social Lead,Remote - Anywhere,"web3, full-stack, technical, support, software..."
3,The Biz Conquest,Mobile Developer,,"dev, engineer, mobiledev, react native"
4,Virta Health,Backend Software Engineer Client Group,,"software, frontend, security, training, full-s..."